### ISSUE TITLE
Rendering issues on smartphones

### ISSUE THREAD

**Issue by huxley** [UnionDesign/andra2016#7]
Got a report from Julian:

Bottom of menu seems to misreader after click

![img_1893](https://cloud.githubusercontent.com/assets/839/26446365/17c222e2-411a-11e7-93e1-c91f0ad46b67.PNG)

also:

- Empty bluebar seems to add some inner lines
- Text is very tight against edge
- Footer menu is non-clickable

**Comment by UnionDesign** [comment]
1. Auxiliary was getting 0 height across the board due to my non-clickable auxiliary nav fix... changed height to "auto" on mobile to fix this issue
2. Padding issue on mobile should be fixed
3. No problem clicking links in footer (can't replicate) but the child pages do disappear at small screen sizes. That was intentional. Idea was uses would just use the parent links.
